baseURL = 'https://www.yduman.dev'
title = "yduman.dev"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
pagination.pagerSize = 20

[markup.highlight]
style = "dracula"

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Yadullah Duman"
info = "is a caffeine driven developer"
description = "Digital Garden of Yadullah Duman"
keywords = "blog,developer,personal"
since = 2018
colorScheme = "auto"
hideColorSchemeToggle = false
avatarurl = "images/Profile.jpg"
capitalizeListTitles = false
enableTwemoji = true
customCSS = ["css/custom.css"]
faviconSVG = "/images/favicon.svg"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/yduman/"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 2
url = "https://bsky.app/profile/y-duman.bsky.social"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/yadullah-duman-601594137"

[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"

[[menu.main]]
name = "About"
weight = 2
url = "about/"

[[menu.main]]
name = "Uses"
weight = 3
url = "uses/"

[[menu.main]]
name = "Projects"
weight = 4
url  = "projects/"


