name: Deploy to GitHub Pages Repo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages Repo
        uses: s0/git-publish-subdir-action@develop
        with:
          publish_dir: public
          token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          destination_repo: yduman/yduman.github.io
          destination_branch: main
          commit_message: "Deployment ${{ env.CURRENT_DATE }}"
          user_name: GitHub Actions
          user_email: actions@github.com
